default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: localhost
  port: 3306
  username: root
  password:

development:
  <<: *default
  database: ntust_senior_chatbot_development

test:
  <<: *default
  database: ntust_senior_chatbot_test

production:
  <<: *default
  database: ntust_senior_chatbot_production