default: &default
  adapter: postgresql
  encoding: unicode


development:
  <<: *default
  database: ntust_senior_chatbot_development

test:
  <<: *default
  database: ntust_senior_chatbot_test

production:
  <<: *default
  database: ntust_senior_chatbot_production